
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-serv
spec:
  type: ClusterIP
  selector:
    app: commandservice
  ports:
  - name : commandservice
    protocol: TCP
    port: 80
    targetPort: 80




        #kubectl version
        #kubectl apply -f .\plateforms-depl.yaml
        #kubectl get  deployments
        #kubectl get pods  
        #kubectl delete deployments plateforms-depl