apiVersion : v1
kind: Service
metadata:
  name: plateformservice-srv
spec:
  type : NodePort
  selector:
    app: plateformservice
  ports:
  -  name: plateformservice
     port: 80
     targetPort: 80

#  kubectl get Services 